[package]
name = "tisp-backend"
version.workspace = true
edition.workspace = true

[dependencies]
tisp-core.workspace = true
tisp-middle.workspace = true
tisp-runtime.workspace = true
miette.workspace = true
thiserror.workspace = true

[features]
default = []
llvm = ["dep:inkwell", "dep:llvm-sys"]
ffi = ["dep:libloading"]

[dependencies.inkwell]
workspace = true
optional = true

[dependencies.llvm-sys]
workspace = true
optional = true

[dependencies.libloading]
workspace = true
optional = true

[dev-dependencies]
tisp-frontend = { workspace = true }
